# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
	tabs:
		first_tab:
			label: Display
			fields:
				next_prev_buttons_loop:
					plugin_setting:
						name: next_prev_buttons_loop
					label: 'Loop next/previous buttons:'
					type: checkbox
					value: ""
					note_below: |
						I.e. pressing the Next button on the last tab goes to the first tab.
													Only applies to Frameworks with Next/Previous buttons.
		size:
			label: Size
			fields:
				set_max_height:
					plugin_setting:
						name: set_max_height
					label: 'Set a maximum height for each Plugin:'
					type: checkbox
					value: ""
					format_onchange: Yes
				max_height:
					plugin_setting:
						name: max_height
					label: 'Maximum height:'
					type: text
					maxlength: "50"
					value: 400px
				desc:
					full_width: Yes
					snippet:
						html: |
							The following settings let you set default values to apply to Banner Plugins that have an image.
															The values you choose here will apply to every Banner, unless overridden by settings of individual Banners.
	module_class_name: zenario_plugin_tabbed_nest
